import './globals.css'
import { personalData } from '@/data/data-page'
import Sidebar from './components/sidebar';

//export const metadata = {
  //title: 'Create Next App',
  //description: 'Generated by create next app',
//}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
      <Sidebar data = {personalData} />
      {children}
      </body>
    </html>
  )
}
